-- MySQL Script generated by MySQL Workbench
-- Fri Apr 20 11:22:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`album_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`album_item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`album_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `comment` VARCHAR(45) NULL,
  `content_id` INT NULL,
  `creation_ts` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gallery_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`gallery_item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`gallery_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `creation_ts` DATETIME NULL,
  `comment` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`photo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`photo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `photo_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`album_item` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `photo_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`gallery_item` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gallery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`gallery` ;

CREATE TABLE IF NOT EXISTS `mydb`.`gallery` (
  `name` VARCHAR(45) NULL COMMENT '\n\n\n',
  `state` INT NULL COMMENT 'State: Is the gallery in edit or final mode?',
  `visibility` INT NULL COMMENT 'visibility: Who is allowed to see this gallery?',
  `creator_id` INT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `creation_ts` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `item_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`gallery_item` ()
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`album` ;

CREATE TABLE IF NOT EXISTS `mydb`.`album` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `state` INT NULL COMMENT 'State: Is the gallery in edit or final mode?',
  `visiblity` INT NULL COMMENT 'visibility: Who is allowed to see this gallery?',
  `creation_ts` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `album_item_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`album_item` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gallery_item_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`gallery_item` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `creator_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`album_item` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `creator_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`album` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `creator_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`gallery_item` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `creator_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`gallery` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
